import fs from 'fs/promises';
import path from 'path';

/**
 * 飞书报告生成器
 * 将处理后的文章生成为飞书文档格式
 */
export class FeishuReporter {
  constructor() {
    this.outputDir = './output';
  }

  /**
   * 生成飞书文档格式的Markdown
   */
  async generateReport(dataFile) {
    const data = JSON.parse(await fs.readFile(dataFile, 'utf-8'));
    const { grouped, generatedAt, totalArticles } = data;
    
    const date = new Date(generatedAt).toLocaleDateString('zh-CN');
    
    let markdown = `# 🤖 AI应用方向信息日报

> 📅 生成时间: ${date}  
> 📊 总计: ${totalArticles} 篇文章  
> 🔄 数据来源: Daniel Miessler RSS

---

`;

    // 按重要性排序的精选文章
    const topArticles = Object.values(grouped)
      .flat()
      .sort((a, b) => b.importance - a.importance)
      .slice(0, 5);

    markdown += `## 🔥 今日精选 (Top 5)

`;
    topArticles.forEach((article, i) => {
      markdown += `### ${i + 1}. ${article.title}

`;
      markdown += `- **来源**: ${article.source}  
`;
      markdown += `- **分类**: ${article.category}  
`;
      markdown += `- **发布时间**: ${new Date(article.pubDate).toLocaleDateString('zh-CN')}  
`;
      markdown += `- **重要性**: ${'⭐'.repeat(Math.floor(article.importance / 2))}  
`;
      markdown += `- **链接**: [阅读原文](${article.link})  

`;
      markdown += `> ${article.summary}\n\n`;
      markdown += `---\n\n`;
    });

    // 按类别分组
    markdown += `## 📑 分类浏览\n\n`;
    
    for (const [category, articles] of Object.entries(grouped)) {
      markdown += `### ${category} (${articles.length}篇)\n\n`;
      
      articles.forEach(article => {
        markdown += `#### ${article.title}\n\n`;
        markdown += `- 📅 ${new Date(article.pubDate).toLocaleDateString('zh-CN')}  `;
        markdown += `| ⭐ ${article.importance}/10  `;
        markdown += `| [阅读](${article.link})\n\n`;
        markdown += `> ${article.summary}\n\n`;
      });
      
      markdown += `\n`;
    }

    // 添加系统说明
    markdown += `---

## ℹ️ 关于本系统

本系统基于 [PAI (Personal AI Infrastructure)](https://github.com/danielmiessler/Personal_AI_Infrastructure) 理念构建：

- **目标导向**: 聚焦AI应用方向的信息搜集
- **持续学习**: 根据阅读反馈优化推荐
- **用户中心**: 以你的需求为核心，非技术展示

### 下一步优化方向

1. ⏰ 自动化定时抓取
2. 📚 支持更多RSS源
3. 🎯 个性化推荐
4. 🔍 全文检索
5. 💬 用户反馈收集

---

*Generated by AI News Collector MVP*
`;

    return markdown;
  }

  /**
   * 保存报告到文件
   */
  async saveReport(dataFile) {
    const markdown = await this.generateReport(dataFile);
    const outputFile = dataFile.replace('.json', '.md');
    
    await fs.writeFile(outputFile, markdown, 'utf-8');
    console.log(`📝 飞书文档格式报告已生成: ${outputFile}`);
    
    return { markdown, outputFile };
  }
}

// CLI入口
async function main() {
  const reporter = new FeishuReporter();
  
  // 找到最新的digest文件
  const files = await fs.readdir('./output');
  const digestFiles = files.filter(f => f.startsWith('digest-') && f.endsWith('.json'));
  
  if (digestFiles.length === 0) {
    console.log('⚠️ 没有找到数据文件，请先运行 npm run collect');
    return;
  }
  
  // 按文件名排序，取最新的
  digestFiles.sort().reverse();
  const latestFile = path.join('./output', digestFiles[0]);
  
  console.log('📝 正在生成报告...');
  const result = await reporter.saveReport(latestFile);
  
  console.log('\n' + '═'.repeat(50));
  console.log('报告预览 (前500字符):');
  console.log('═'.repeat(50));
  console.log(result.markdown.substring(0, 500) + '...');
}

main().catch(console.error);